[project]
name = "eventhub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Miss shelby", email = "ceeyntia@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "sqlmodel>=0.0.42",
]

[project.scripts]
eventhub = "eventhub:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
extraPaths = ["."]
