"""initial migration

Revision ID: 0b2600fe5fc7
Revises: 
Create Date: 2026-09-11 14:41:24.678091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2600fe5fc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_time', sa.Time(), server_default='00:00:00', nullable=False))
    op.add_column('events', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('events', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using='date::timestamp')
    op.drop_column('events', 'image')
    op.drop_column('events', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('events', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('events', 'images')
    op.drop_column('events', 'event_time')
    # ### end Alembic commands ###
